
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DetailWareHouse
{

    public int Id { get; set; }

    public string IdWareHouse { get; set; }

    public string IdGoods { get; set; }

    public Nullable<double> Inventory { get; set; }

    public Nullable<bool> Status { get; set; }



    public virtual Good Good { get; set; }

    public virtual WareHouse WareHouse { get; set; }

}

}
