//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailStock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetailStock()
        {
            this.DetailStockEpcs = new HashSet<DetailStockEpc>();
        }
    
        public string Id { get; set; }
        public string IdWareHouse { get; set; }
        public string IdGoods { get; set; }
        public string IdStock { get; set; }
        public Nullable<double> QuantityInvetory { get; set; }
        public Nullable<double> QuantityStock { get; set; }
        public Nullable<double> Suffice { get; set; }
        public Nullable<double> Incomplete { get; set; }
        public Nullable<double> Residual { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Stock Stock { get; set; }
        public virtual WareHouse WareHouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailStockEpc> DetailStockEpcs { get; set; }
    }
}
