
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Models
{

using System;
    using System.Collections.Generic;
    
    public partial class DetailGoodOrder
    {
        public int Id { get; set; }
        public string IdGoods { get; set; }
        public string IdReceipt { get; set; }
        public string IdPurchaseOrder { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> QuantityScan { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Receipt Receipt { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
