//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Function
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Function()
        {
            this.ParentFolders = new HashSet<ParentFolder>();
            this.ParamFunctions = new HashSet<ParamFunction>();
        }
    
        public string Id { get; set; }
        public string IdMenu { get; set; }
        public string Name { get; set; }
        public string NameFunctionAPI { get; set; }
        public string ReturnJson { get; set; }
        public string StatusReturnJson { get; set; }
        public string NameReturnJson { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Method { get; set; }
        public string ReturnValue { get; set; }
    
        public virtual Menu Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParentFolder> ParentFolders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParamFunction> ParamFunctions { get; set; }
    }
}
