//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Good()
        {
            this.DetailGoodOrders = new HashSet<DetailGoodOrder>();
            this.DetailSaleOrders = new HashSet<DetailSaleOrder>();
            this.DetailStocks = new HashSet<DetailStock>();
            this.DetailWareHouses = new HashSet<DetailWareHouse>();
            this.EPCs = new HashSet<EPC>();
        }
    
        public string Id { get; set; }
        public string IdWareHouse { get; set; }
        public string IdUnit { get; set; }
        public string IdGroupGood { get; set; }
        public string Name { get; set; }
        public Nullable<double> Inventory { get; set; }
        public Nullable<double> MinimumInventory { get; set; }
        public Nullable<double> MaximumInventory { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Line { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailGoodOrder> DetailGoodOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailSaleOrder> DetailSaleOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailStock> DetailStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailWareHouse> DetailWareHouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EPC> EPCs { get; set; }
        public virtual GroupGood GroupGood { get; set; }
        public virtual WareHouse WareHouse { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
