
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class InventoryNotify
{

    public int Id { get; set; }

    public string IdWareHouse { get; set; }

    public string Warehouse { get; set; }

    public string IdGoods { get; set; }

    public string Goods { get; set; }

    public Nullable<double> NewInventory { get; set; }

    public string Message { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string UserName { get; set; }

    public Nullable<System.DateTime> ModifyDate { get; set; }

    public string ModifyBy { get; set; }

}

}
