
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WMS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Receipt
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Receipt()
    {

        this.DetailGoodOrders = new HashSet<DetailGoodOrder>();

        this.SalesOrders = new HashSet<SalesOrder>();

    }


    public string Id { get; set; }

    public string IdPurchaseOrder { get; set; }

    public string IdUser1 { get; set; }

    public string IdUser2 { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string CreateBy { get; set; }

    public Nullable<System.DateTime> ModifyDate { get; set; }

    public string ModifyBy { get; set; }

    public Nullable<bool> Status { get; set; }

    public Nullable<System.DateTime> ExpiryDate { get; set; }

    public Nullable<System.DateTime> AnnouceDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DetailGoodOrder> DetailGoodOrders { get; set; }

    public virtual PurchaseOrder PurchaseOrder { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SalesOrder> SalesOrders { get; set; }

}

}
