//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string Id { get; set; }
        public string User1 { get; set; }
        public string Pass { get; set; }
        public string Name { get; set; }
        public string AddRess { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public string Phone { get; set; }
        public string Description { get; set; }
        public Nullable<int> RoleAdmin { get; set; }
        public Nullable<int> Role { get; set; }
        public string WorkingHour { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> FailPass { get; set; }
    
        public virtual Role Role1 { get; set; }
        public virtual RoleAdmin RoleAdmin1 { get; set; }
    }
}
